
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./components/animations.css";

import ClientNavbarWrapper from "./components/ClientNavbarWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  // Next.js App Router: usePathname only works in client components
  // So, we need to make this layout a client component
  // Add 'use client' directive
  // Only show Navbar if not on admin route
  // This works for all routes that do NOT start with /admin-
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
  {/* Navbar user hanya muncul di halaman user, pengecekan di komponen client */}
  <ClientNavbarWrapper>{children}</ClientNavbarWrapper>
      </body>
    </html>
  );
}

